import React from "react";

function Icon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="69"
      height="59"
      fill="none"
      viewBox="0 0 69 59"
    >
      <circle cx="37.267" cy="20.856" r="20.856" fill="#FFCB13"></circle>
      <g filter="url(#filter0_f_98_1209)">
        <ellipse
          cx="17.492"
          cy="29.38"
          fill="#fff"
          fillOpacity="0.5"
          rx="3.628"
          ry="3.644"
        ></ellipse>
      </g>
      <g filter="url(#filter1_f_98_1209)">
        <ellipse
          cx="19.306"
          cy="30.595"
          fill="#fff"
          fillOpacity="0.5"
          rx="3.628"
          ry="3.644"
        ></ellipse>
      </g>
      <g filter="url(#filter2_f_98_1209)">
        <ellipse
          cx="23.237"
          cy="29.38"
          fill="#fff"
          fillOpacity="0.5"
          rx="3.628"
          ry="3.644"
        ></ellipse>
      </g>
      <g filter="url(#filter3_f_98_1209)">
        <ellipse
          cx="26.563"
          cy="30.595"
          fill="#fff"
          fillOpacity="0.5"
          rx="3.628"
          ry="3.644"
        ></ellipse>
      </g>
      <g filter="url(#filter4_f_98_1209)">
        <ellipse
          cx="17.492"
          cy="29.38"
          fill="#fff"
          fillOpacity="0.5"
          rx="3.628"
          ry="3.644"
        ></ellipse>
      </g>
      <g filter="url(#filter5_f_98_1209)">
        <ellipse
          cx="19.306"
          cy="30.595"
          fill="#fff"
          fillOpacity="0.5"
          rx="3.628"
          ry="3.644"
        ></ellipse>
      </g>
      <g filter="url(#filter6_f_98_1209)">
        <ellipse
          cx="23.237"
          cy="29.38"
          fill="#fff"
          fillOpacity="0.5"
          rx="3.628"
          ry="3.644"
        ></ellipse>
      </g>
      <g filter="url(#filter7_f_98_1209)">
        <ellipse
          cx="26.563"
          cy="30.595"
          fill="#fff"
          fillOpacity="0.5"
          rx="3.628"
          ry="3.644"
        ></ellipse>
      </g>
      <path
        fill="#4A4A4A"
        d="M32.177 7.934c.769-1.337 2.699-1.337 3.468 0l19.848 34.53c.767 1.333-.196 2.996-1.733 2.996H14.062c-1.538 0-2.5-1.663-1.734-2.996l19.849-34.53z"
      ></path>
      <rect
        width="53.822"
        height="20.347"
        x="7"
        y="34.918"
        fill="#AF9393"
        rx="10"
      ></rect>
      <rect width="69" height="13" y="42.918" fill="#726464" rx="3"></rect>
      <g filter="url(#filter8_f_98_1209)">
        <ellipse
          cx="50.903"
          cy="20.877"
          fill="#fff"
          fillOpacity="0.5"
          rx="3.628"
          ry="3.644"
        ></ellipse>
      </g>
      <g filter="url(#filter9_f_98_1209)">
        <ellipse
          cx="52.718"
          cy="22.091"
          fill="#fff"
          fillOpacity="0.5"
          rx="3.628"
          ry="3.644"
        ></ellipse>
      </g>
      <g filter="url(#filter10_f_98_1209)">
        <ellipse
          cx="56.648"
          cy="20.877"
          fill="#fff"
          fillOpacity="0.5"
          rx="3.628"
          ry="3.644"
        ></ellipse>
      </g>
      <g filter="url(#filter11_f_98_1209)">
        <ellipse
          cx="59.975"
          cy="22.091"
          fill="#fff"
          fillOpacity="0.5"
          rx="3.628"
          ry="3.644"
        ></ellipse>
      </g>
      <g filter="url(#filter12_f_98_1209)">
        <ellipse
          cx="50.903"
          cy="20.877"
          fill="#fff"
          fillOpacity="0.5"
          rx="3.628"
          ry="3.644"
        ></ellipse>
      </g>
      <g filter="url(#filter13_f_98_1209)">
        <ellipse
          cx="52.718"
          cy="22.091"
          fill="#fff"
          rx="3.628"
          ry="3.644"
        ></ellipse>
      </g>
      <g filter="url(#filter14_f_98_1209)">
        <ellipse
          cx="56.648"
          cy="20.877"
          fill="#fff"
          rx="3.628"
          ry="3.644"
        ></ellipse>
      </g>
      <g filter="url(#filter15_f_98_1209)">
        <ellipse
          cx="59.975"
          cy="22.091"
          fill="#fff"
          fillOpacity="0.5"
          rx="3.628"
          ry="3.644"
        ></ellipse>
      </g>
      <defs>
        <filter
          id="filter0_f_98_1209"
          width="15.257"
          height="15.289"
          x="9.863"
          y="21.736"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur_98_1209"
            stdDeviation="2"
          ></feGaussianBlur>
        </filter>
        <filter
          id="filter1_f_98_1209"
          width="15.257"
          height="15.289"
          x="11.678"
          y="22.95"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur_98_1209"
            stdDeviation="2"
          ></feGaussianBlur>
        </filter>
        <filter
          id="filter2_f_98_1209"
          width="15.257"
          height="15.289"
          x="15.608"
          y="21.736"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur_98_1209"
            stdDeviation="2"
          ></feGaussianBlur>
        </filter>
        <filter
          id="filter3_f_98_1209"
          width="15.257"
          height="15.289"
          x="18.934"
          y="22.95"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur_98_1209"
            stdDeviation="2"
          ></feGaussianBlur>
        </filter>
        <filter
          id="filter4_f_98_1209"
          width="15.257"
          height="15.289"
          x="9.863"
          y="21.736"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur_98_1209"
            stdDeviation="2"
          ></feGaussianBlur>
        </filter>
        <filter
          id="filter5_f_98_1209"
          width="15.257"
          height="15.289"
          x="11.678"
          y="22.95"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur_98_1209"
            stdDeviation="2"
          ></feGaussianBlur>
        </filter>
        <filter
          id="filter6_f_98_1209"
          width="15.257"
          height="15.289"
          x="15.608"
          y="21.736"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur_98_1209"
            stdDeviation="2"
          ></feGaussianBlur>
        </filter>
        <filter
          id="filter7_f_98_1209"
          width="15.257"
          height="15.289"
          x="18.934"
          y="22.95"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur_98_1209"
            stdDeviation="2"
          ></feGaussianBlur>
        </filter>
        <filter
          id="filter8_f_98_1209"
          width="15.257"
          height="15.289"
          x="43.275"
          y="13.232"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur_98_1209"
            stdDeviation="2"
          ></feGaussianBlur>
        </filter>
        <filter
          id="filter9_f_98_1209"
          width="15.257"
          height="15.289"
          x="45.089"
          y="14.447"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur_98_1209"
            stdDeviation="2"
          ></feGaussianBlur>
        </filter>
        <filter
          id="filter10_f_98_1209"
          width="15.257"
          height="15.289"
          x="49.02"
          y="13.232"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur_98_1209"
            stdDeviation="2"
          ></feGaussianBlur>
        </filter>
        <filter
          id="filter11_f_98_1209"
          width="15.257"
          height="15.289"
          x="52.346"
          y="14.447"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur_98_1209"
            stdDeviation="2"
          ></feGaussianBlur>
        </filter>
        <filter
          id="filter12_f_98_1209"
          width="15.257"
          height="15.289"
          x="43.275"
          y="13.232"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur_98_1209"
            stdDeviation="2"
          ></feGaussianBlur>
        </filter>
        <filter
          id="filter13_f_98_1209"
          width="15.257"
          height="15.289"
          x="45.089"
          y="14.447"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur_98_1209"
            stdDeviation="2"
          ></feGaussianBlur>
        </filter>
        <filter
          id="filter14_f_98_1209"
          width="15.257"
          height="15.289"
          x="49.02"
          y="13.232"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur_98_1209"
            stdDeviation="2"
          ></feGaussianBlur>
        </filter>
        <filter
          id="filter15_f_98_1209"
          width="15.257"
          height="15.289"
          x="52.346"
          y="14.447"
          colorInterpolationFilters="sRGB"
          filterUnits="userSpaceOnUse"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix"></feFlood>
          <feBlend
            in="SourceGraphic"
            in2="BackgroundImageFix"
            result="shape"
          ></feBlend>
          <feGaussianBlur
            result="effect1_foregroundBlur_98_1209"
            stdDeviation="2"
          ></feGaussianBlur>
        </filter>
      </defs>
    </svg>
  );
}

export default Icon;
